### PR TITLE
Remove python 2 support

### PR DESCRIPTION
**Pull request by ptmerz**
## Description
Python 2 is out of support since a year, and it's time to get rid of it.
This only changes the supported version, and 
removes `__future__` imports related to python 2. This refs #47, 
but more work is needed before we close the issue.

There's still some work arounds we want to get rid of, but for now,
we're trying to avoid large code changes before we have more
testing. On the other hand, we want to avoid having to introduce more
workarounds when introducing tests.

### CODE REVIEW

**Comment by ptmerz** [comment]
@mattwthompson or @SimonBoothroyd, any idea what I broke here? https://github.com/shirtsgroup/physical_validation/pull/80/checks?check_run_id=1527737442

It seems like a version conflict, but I'm not sure what I should have updated to avoid this!

**Comment by mattwthompson** [comment]
The environment couldn't be activated because it wasn't created - the previous step shows the conflicts (not in a useful way) but the error code wasn't reported, so the failures didn't go through to the UI.

The root cause seems to be that `pymbar` is not yet built on Python 3.9: https://anaconda.org/conda-forge/pymbar/files, maybe see https://github.com/conda-forge/pymbar-feedstock/pull/9? I'm less familiar with how that project is packaged.

**Comment by mattwthompson** [comment]
If this get hairy, another option would be to replace these scripts with [this](https://github.com/conda-incubator/setup-miniconda) action. It may not be worth the switchover, since the scripts don't seem to be the issue here, but it's an option if they become one.

**Comment by ptmerz** [comment]
I see, thanks for the explanation. Refs #48.

I'll remove 3.9 for now, then. Main goal of this PR is to get rid of Py2. Opened a new issue for 3.9: #82

**Comment by mrshirts** [comment]
I posted an issue with pymbar here: https://github.com/choderalab/pymbar/issues/420. Not sure the best workaround in the meantime!

**Review by SimonBoothroyd — APPROVED** [review]
LGTM!

**Pull request merged**
