### PR TITLE
Add pre-commit

### PR DESCRIPTION
**Pull request by mattwthompson**
A bot from https://pre-commit.ci should run in and automatically run `black` with its most recent version

### CODE REVIEW

**Comment by mattwthompson** [comment]
I was wrong, somebody with more permissions in the organization would need to allow the App to access this repo: https://github.com/marketplace/pre-commit-ci

**Comment by ptmerz** [comment]
> I was wrong, somebody with more permissions in the organization would need to allow the App to access this repo: https://github.com/marketplace/pre-commit-ci

I think only @mrshirts can do that!

**Comment by mrshirts** [comment]
Did I manage to activate it correctly?

**Comment by mattwthompson** [comment]
Probably - although I think it's likely the bot won't run until the config file exists on the default branch (i.e. until this is merged). So I didn't give sufficient instructions when asking for help, sorry!

@ptmerz would you consider reviewing this as-is? The changes to the source code are only because of black's recent update. You're probably familiar with git hooks but you could verifiy things locally with i.e.

```
$ git checkout upstream/add-pre-commit
$ pip install pre-commit
$ pre-commit install
$ pre-commit run --all-files
```

Depending on interest and effort there's plenty more cool stuff that can be done. But my goal here was only to update with the new version of black and set up automation so that a bot would do it the next time there's an update.

**Review by ptmerz — APPROVED** [review]
This looks great, thank you @mattwthompson. I played around a bit locally, happy to approve!

**Pull request merged**
